# Generated by Django 4.0.5 on 2022-06-13 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apprate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='apprate.post'),
        ),
    ]
